export type Product = {
  slug: string
  name: string
  category: string
  price: number
  priceMax?: number
  badge: string | null
  temperature: string | null
  autonomy: string | null
  material: string
  sizes: string[]
  image: string
  description: string
  benefits: string[]
}

export const products: Product[] = [
  {
    slug: 'thermal-short-adult',
    name: 'Thermal Short Adult',
    category: 'Recovery Wear',
    price: 100,
    badge: null,
    temperature: '10–15°C',
    autonomy: '+60 min',
    material: '80% Polyester / 20% Elastane',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/11/COLD2SPORT25294.jpg',
    description: 'Cold2Sport cooling pants designed for post-exercise muscle recovery. High compression and comfort with precise cooling transfer within 10–15°C, maintaining optimal temperature for over 1 hour.',
    benefits: [
      'High compression and comfort',
      'Precise cooling transfer 10–15°C',
      'Over 1 hour autonomy',
      'Side pockets and elastic drawstring',
      'BioFresh Tech PCM technology',
      'Machine washable at 30°C',
      'Eco-certified materials',
    ],
  },
  {
    slug: 'cooling-knee-pad',
    name: 'Thermal Knee Pad',
    category: 'Joint Recovery',
    price: 45,
    badge: 'New',
    temperature: '5–15°C',
    autonomy: '+55 min',
    material: 'Technical textile / PCM gel',
    sizes: ['S', 'M', 'L', 'XL'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/12/C2S-2025-07-09-0121.jpg',
    description: 'Advanced cold therapy knee brace combining therapeutic cooling with ergonomic design. Cold points positioned at frontal bursae and posterior areas for targeted recovery.',
    benefits: [
      'Targeted cold point positioning',
      'Ergonomic anatomical design',
      'Frontal and posterior coverage',
      'Adjustable compression',
      'Lightweight and portable',
      'Reusable PCM gel',
      'Medical-grade materials',
    ],
  },
  {
    slug: 'ankle-brace',
    name: 'Cold Ankle Brace',
    category: 'Joint Recovery',
    price: 45,
    badge: 'New',
    temperature: '10–15°C',
    autonomy: '+50 min',
    material: 'Nylon / Velvet reversible',
    sizes: ['S/M', 'L/XL'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/12/turmellera-quadrat-1.jpg',
    description: 'Thermal ankle brace with reversible design for dual thermal therapy. Nylon side for intense cold, velvet side for gentle cooling. Homogeneous gel distribution for stable temperature.',
    benefits: [
      'Reversible dual therapy design',
      'Nylon side for intense cold',
      'Velvet side for gentle cooling',
      'Homogeneous gel distribution',
      'Stable temperature maintenance',
      'Compact and portable',
      'Anti-odour treatment',
    ],
  },
  {
    slug: 'versatil-coldpack',
    name: 'Versatil ColdPack',
    category: 'Joint Recovery',
    price: 50,
    badge: null,
    temperature: '10–15°C',
    autonomy: '+120 min',
    material: 'Nylon / Velvet reversible',
    sizes: ['One Size'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/12/mosaic-versatil-3.jpg',
    description: 'Versatile cold therapy belt for muscle and joint relief on any body area. Dual thermal therapy with reversible nylon and velvet sides, maintaining 10–15°C for up to 2 hours.',
    benefits: [
      'Universal body fit',
      'Up to 2 hours autonomy',
      'Dual thermal therapy',
      'Adjustable belt system',
      'No freezer needed',
      'Travel-friendly',
      'BPA-free materials',
    ],
  },
  {
    slug: 'backpack-for-garments',
    name: 'Backpack for Garments',
    category: 'Storage',
    price: 45,
    badge: null,
    temperature: null,
    autonomy: '+4 hours',
    material: 'Technical polyester',
    sizes: ['One Size'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/11/COLD2SPORT25280.jpg',
    description: 'Thermal backpack that maintains technical garments at optimal temperature away from home. Includes 3 IcePacks for 4+ hours of temperature maintenance with temperature display.',
    benefits: [
      'Includes 3 IcePacks',
      '4+ hours temperature maintenance',
      'Temperature display',
      'Fits full Thermal Short kit',
      'Separate compartments',
      'Water-resistant exterior',
      'Ergonomic straps',
    ],
  },
  {
    slug: 'premium-thermo-bag',
    name: 'Premium Thermal-Bag + Bottle',
    category: 'Beverage',
    price: 48,
    badge: null,
    temperature: null,
    autonomy: '+10 hours',
    material: 'Neoprene + thermal insulation',
    sizes: ['One Size'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/12/cold2sport-funda-display-01-scaled.jpg',
    description: 'Advanced thermal bag with BioFreshTech coolant technology. Maintains beverages at 10°C for over 10 hours. Includes temperature display, adjustable neoprene handles, and thermos bottle.',
    benefits: [
      '10+ hours at 10°C',
      'Temperature display included',
      'Includes thermos bottle',
      'Adjustable neoprene handles',
      'BioFreshTech coolant',
      'Professional grade',
      'Competition ready',
    ],
  },
  {
    slug: 'basic-thermo-bag',
    name: 'Basic Thermal-Bag',
    category: 'Beverage',
    price: 25,
    badge: null,
    temperature: null,
    autonomy: '+4 hours',
    material: 'Insulated nylon',
    sizes: ['One Size'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/11/COLD2SPORT25241-1.jpg',
    description: 'Thermal bag with natural coolant BioFreshTech. Keeps beverages at 10°C for over 4 hours. Compatible with 330ml, 500ml, and 750ml bottles.',
    benefits: [
      '4+ hours at 10°C',
      'BioFreshTech coolant',
      'Multi-bottle compatible',
      'Compact and portable',
      'Natural coolant',
      'Hand washable',
      'Everyday use',
    ],
  },
  {
    slug: 'cold2sport-ice-pack',
    name: 'ColdPack Cold2Sport',
    category: 'Accessories',
    price: 7.99,
    priceMax: 20,
    badge: null,
    temperature: null,
    autonomy: null,
    material: 'PCM gel',
    sizes: ['Small', 'Large'],
    image: 'https://cold2sport.com/wp-content/uploads/2025/04/icepack-cold2sport-thermal.jpeg',
    description: 'Ice pack designed for recovery and pain relief. Advanced cooling technology with gel formula, ergonomic design fitting various body parts, and lightweight portability.',
    benefits: [
      'Advanced gel formula',
      'Ergonomic body fit',
      'Lightweight and portable',
      'Reusable',
      'Multi-size options',
      'Rapid cooling',
      'Affordable recovery',
    ],
  },
  {
    slug: 'cooling-bottle',
    name: 'Thermos Bottle',
    category: 'Beverage',
    price: 25,
    badge: null,
    temperature: null,
    autonomy: null,
    material: 'Stainless steel',
    sizes: ['500ml', '750ml'],
    image: 'https://cold2sport.com/wp-content/uploads/2024/12/thermos-bottle-cold2sport-1.jpg',
    description: 'Double top closure system for drink insulation. High-tech thermal insulation compatible with Basic and Premium thermo-bags. Extremely lightweight.',
    benefits: [
      'Double closure system',
      'High-tech insulation',
      'Compatible with thermo-bags',
      'Extremely lightweight',
      'BPA-free',
      'Dishwasher safe lid',
      'Cold2Sport branding',
    ],
  },
]

export const categories = [...new Set(products.map((p) => p.category))]
