export type Product = {
  slug: string
  name: string
  category: string
  price: number
  badge: string | null
  temperature: string | null
  autonomy: string | null
  material: string
  sizes: string[]
  image: string
  description: string
  benefits: string[]
}

export const products: Product[] = [
  {
    slug: 'thermal-short',
    name: 'Thermal Short',
    category: 'Recovery Wear',
    price: 89.95,
    badge: 'Bestseller',
    temperature: '10–15°C',
    autonomy: '+60 min',
    material: '80% Polyester / 20% Elastane',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80',
    description: 'The flagship recovery garment. Delivers sustained cooling to quads, hamstrings and glutes immediately after training or competition.',
    benefits: [
      'Reduces muscle inflammation',
      'Accelerates metabolic waste clearance',
      'Improves sleep quality post-match',
      'BioFresh Tech PCM capsules embedded',
      'Compression fit for better circulation',
      'Machine washable at 30°C',
      'Eco-certified materials',
    ],
  },
  {
    slug: 'versatil-coldpack',
    name: 'Versatil ColdPack',
    category: 'Joint Recovery',
    price: 34.95,
    badge: null,
    temperature: '8–12°C',
    autonomy: '+45 min',
    material: 'Neoprene exterior / PCM interior',
    sizes: ['One Size'],
    image: 'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=600&q=80',
    description: 'Flexible cold pack adaptable to any body part. Ideal for knees, shoulders and ankles.',
    benefits: [
      'Universal fit',
      'Reusable — no freezer needed',
      'Activates on contact with skin',
      'Lightweight (180g)',
      'Travel-friendly',
      'Medical-grade PCM',
      'BPA-free materials',
    ],
  },
  {
    slug: 'thermal-anklet',
    name: 'Thermal Anklet',
    category: 'Joint Recovery',
    price: 44.95,
    badge: null,
    temperature: '10–15°C',
    autonomy: '+50 min',
    material: '75% Polyester / 25% Elastane',
    sizes: ['S/M', 'L/XL'],
    image: 'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=600&q=80',
    description: 'Targeted cooling for ankle ligaments and tendons. Essential for runners and football players.',
    benefits: [
      'Ankle sprain prevention aid',
      'Post-training recovery',
      'Fits under socks',
      'No velcro — smooth inner',
      'Bilateral symmetry (left/right)',
      'BioFresh PCM integrated',
      'Anti-odour treatment',
    ],
  },
  {
    slug: 'thermal-knee-pad',
    name: 'Thermal Knee Pad',
    category: 'Joint Recovery',
    price: 54.95,
    badge: 'New',
    temperature: '10–15°C',
    autonomy: '+55 min',
    material: '78% Polyester / 22% Elastane',
    sizes: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80',
    description: 'Anatomical knee sleeve with integrated BioFresh cooling panels targeting the patellar tendon.',
    benefits: [
      'Patellar tendon support',
      'Post-surgery recovery aid',
      'Graduated compression',
      'Open-patella design',
      'Moisture wicking',
      'Reinforced seams',
      'Certified medical device',
    ],
  },
  {
    slug: 'backpack',
    name: 'Recovery Backpack',
    category: 'Storage',
    price: 79.95,
    badge: null,
    temperature: null,
    autonomy: null,
    material: '600D Polyester',
    sizes: ['One Size'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    description: 'Insulated backpack with dedicated compartment to store and transport your Cold2Sport garments.',
    benefits: [
      'Insulated main compartment',
      'Fits full Thermal Short kit',
      'Separate wet/dry zones',
      '30L capacity',
      'Padded laptop sleeve',
      'Water-resistant exterior',
      'Ergonomic shoulder straps',
    ],
  },
  {
    slug: 'premium-thermal-bag',
    name: 'Premium Thermal Bag',
    category: 'Storage',
    price: 59.95,
    badge: null,
    temperature: null,
    autonomy: null,
    material: 'EVA foam + Nylon exterior',
    sizes: ['One Size'],
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    description: 'Rigid thermal case for professional use. Keeps garments at optimal temperature for up to 4 hours.',
    benefits: [
      '4h thermal retention',
      'Rigid EVA protection',
      'Lockable zipper',
      'Handle + shoulder strap',
      'Team branding available',
      'Airport security compliant',
      'Professional grade',
    ],
  },
  {
    slug: 'basic-thermal-bag',
    name: 'Basic Thermal Bag',
    category: 'Storage',
    price: 29.95,
    badge: null,
    temperature: null,
    autonomy: null,
    material: 'Insulated nylon',
    sizes: ['One Size'],
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    description: 'Lightweight thermal bag for everyday recovery. Perfect for gym bag integration.',
    benefits: [
      '2h thermal retention',
      'Compact and foldable',
      'Hand wash only',
      'Two colour options',
      'Fits Thermal Short',
      'Zipper closure',
      'Affordable everyday option',
    ],
  },
  {
    slug: 'thermal-bottle',
    name: 'Thermal Bottle',
    category: 'Beverage',
    price: 24.95,
    badge: null,
    temperature: null,
    autonomy: null,
    material: 'Stainless steel 18/8',
    sizes: ['500ml', '750ml'],
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    description: 'Double-wall vacuum bottle. Keeps cold drinks cold for 24h. Co-branded Cold2Sport + BioFresh.',
    benefits: [
      '24h cold retention',
      'Double-wall vacuum',
      'BPA-free',
      'Leakproof lid',
      'Wide mouth for ice',
      'Dishwasher safe lid',
      'Cold2Sport branding',
    ],
  },
]

export const categories = [...new Set(products.map((p) => p.category))]
